CREATE TABLE Books (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Author NVARCHAR(255) NOT NULL,
    Genre NVARCHAR(100) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL
);

CREATE TABLE Comments (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    BookId UNIQUEIDENTIFIER,
    FOREIGN KEY (BookId) REFERENCES Books(Id)
);